"""drop_is_disabled_column

Revision ID: 10e825eec740
Revises: aa5203126e01
Create Date: 2026-08-22 14:05:37.211320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10e825eec740'
down_revision: Union[str, Sequence[str], None] = 'aa5203126e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_disabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_disabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
