version: '3.8'
services:
  postgres:
    container_name: hethera-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hethera
    volumes:
      - ../.db-volume:/var/lib/postgresql/data
    ports:
      - '5445:5432'
    networks:
      - hethera-postgres
    restart: unless-stopped

networks:
  hethera-postgres:
    driver: bridge
