"""admin refresh tokens and singleton admin constraint

Revision ID: 9f42ef996ed4
Revises: 1b0e46241df1
Create Date: 2026-09-12 16:34:01.605779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f42ef996ed4'
down_revision: Union[str, Sequence[str], None] = '1b0e46241df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['super_admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_refresh_tokens_admin_id'), 'admin_refresh_tokens', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_refresh_tokens_token_hash'), 'admin_refresh_tokens', ['token_hash'], unique=True)
    op.add_column('super_admins', sa.Column('singleton', sa.Integer(), server_default='1', nullable=False))
    op.create_unique_constraint('uq_super_admins_singleton', 'super_admins', ['singleton'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_super_admins_singleton', 'super_admins', type_='unique')
    op.drop_column('super_admins', 'singleton')
    op.drop_index(op.f('ix_admin_refresh_tokens_token_hash'), table_name='admin_refresh_tokens')
    op.drop_index(op.f('ix_admin_refresh_tokens_admin_id'), table_name='admin_refresh_tokens')
    op.drop_table('admin_refresh_tokens')
    # ### end Alembic commands ###
